### ISSUE TITLE
Request: Linux support

### ISSUE THREAD

**Issue by nsde** [ProtossManse/MCAutoSubmit#6]
Please add a .deb release :)
Thanks!
Let me know if you need help or have any questions.

**Comment by ProtossManse** [comment]
I did it!

it isn't a .deb file; It is just a binary executable file.
but you must be root to use Keyboard library on Linux.
So you have to run the app using the command below:

```
sudo ./MCAutoSubmit_v1_2_3_Linux
```

I'm trying to solve this problem.

Thank you.

**Comment by nsde** [comment]
Thanks! :)
